import { SideNav } from '@/components/SideNav'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
  
    <html lang="en">
      <head>
        <title>Haiku-itter</title>
        <meta 
          name='description'
          content='This is a twitter inspired app that only accespts Haikus for posts and comments'
        />
      </head>
      <body className={inter.className}>
        <div className='container mx-auto flex items-start'>
          <SideNav />
          <div className='min-h-screen flex-grow border-x'>
            {children}
          </div>
        </div>
        </body>
    </html>
  )
}
